### ISSUE TITLE
How to track a remote gitlab repo

### ISSUE THREAD

**Issue by at15** [yyx990803/pod#51]
> Starting in 0.8.2, GitLab webhooks are also supported.

But following the guide [using a remote repo](https://github.com/yyx990803/pod/wiki/Using-a-remote-repo), it seems github is the only option for creating remote repo.  So if I use `pod remote foo-app at15/foo` it will track `github.com/at15/foo.git` How can I let pod track repos in self host gitlab instance, like `git.abc.com/at15/foo.git`? Thanks a lot.

**Comment by taylorzane** [comment]
You have to pass it the full git URL. Either `https://git.abc.com/foo/bar.git` or `git@git.abc.com:foo/bar.git`. Also note that pod doesn't track changes. You have to set up a webhook in your repository settings to point to the server that pod is running on, on port 19999 (assuming you haven't changed the default, and don't have port forwarding set up)

**Comment by at15** [comment]
oops, I tried `pod remote foo-app ssh://git@git.abc.com:1234/at15/foo.git` and it works, pod supports normal git remote syntax and it will expands  `username/repo`  to `https://github.com/username/repo`. Found code in https://github.com/yyx990803/pod/blob/master/lib/api.js#L433

btw: since it will expands to`https` not `ssh`, have the ssh key added to private repos won't work. related issue #39 #32  maybe let user choose the protocol if they did not enter a full remote url? @yyx990803

**Comment by at15** [comment]
@taylorzane thanks. I will setup the webhook in gitlab.

**Comment by taylorzane** [comment]
@at15 I can add a command line argument to force ssh. But I feel that just specifying the entire URI would remove the need.

How about this:
1. Have a config var in `.podrc`, `force_ssh: true`
2. If the val is true, try ssh first, if it fails, try https, if that fails...throw an error
3. If `force_ssh` is false/undefined, it tries https, then ssh. 

Any thoughts @yyx990803? I'll submit a PR tomorrow if you would benefit from this @at15. Seems a little better than a CLI arg since initial users don't have to worry about mucking with HTTPS vs SSH, and it "Just Works".

**Comment by at15** [comment]
@taylorzane thanks, I already everything up and running. Maybe the doc in readme and wiki can be updated, so users can know they can specify the entire URI, And tell the user if they use the `username/repo` it will become `https://github.com/username/repo`, otherwise the wiki is somehow misleading, it tells you to add ssh key first and then it uses `https`.

**Comment by taylorzane** [comment]
:+1: agreed. I'll get the docs updated for any other new users.
